### ISSUE TITLE
Deal with constrained least squares

### ISSUE THREAD

**Issue by geoffroyleconte** [JuliaSmoothOptimizers/RipQP.jl#26]
It should be possible and interesting to be able to solve:

`min ||r||²/2  s.t.  Ax + r = b`.

This problem can be formulated as a QP.

**Comment by dpo** [comment]
#33 implements the API.

One algorithmic improvement that you could make for LLS problems is that there is no need to regularize Ax + r = b; it is already regularized.

**Comment by geoffroyleconte** [comment]
fixed with https://github.com/JuliaSmoothOptimizers/RipQP.jl/pull/122
