### ISSUE TITLE
Generate DOI

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/RipQP.jl#8]
- [x] add DOI to CITATION.bib
- [x] add DOI badge to README.md

**Comment by geoffroyleconte** [comment]
@dpo I think I do not have the rights to create a Zenodo DOI with the JSO repo. Should I do it with my own fork?

**Comment by dpo** [comment]
[![DOI](https://zenodo.org/badge/294639241.svg)](https://zenodo.org/badge/latestdoi/294639241)

**Comment by geoffroyleconte** [comment]
Thank you!

**Comment by geoffroyleconte** [comment]
This is fixed, I close the issue.
